# io-stress.yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-stress-test
  namespace: default
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "sample-microservice"
  volumePath: /tmp
  path: "/tmp/**/*"
  delay: "100ms"
  percent: 50
  duration: "1m"
